export enum Config {
    PORT = 'PORT',
    HOST = 'HOST',
    MONGODB_USER = 'MONGODB_USER',
    MONGODB_PASSWORD = 'MONGODB_PASSWORD',
    MONGODB_CLUSTER = 'MONGODB_CLUSTER',
    MONGODB_DATABASE = 'MONGODB_DATABASE',
    MONGODB_OPTIONS = 'MONGODB_OPTIONS',
    GRAPHQL_TYPE_PATHS = 'GRAPHQL_TYPE_PATHS',
    CLOUDINARY_URL = 'CLOUDINARY_URL',
    CLOUDINARY_NAME = 'CLOUDINARY_NAME',
    CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
    CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',
    SECRET_JWT = 'SECRET_JWT',
    SECRET_SALT = 'SECRET_SALT',
    UPLOAD = 'UPLOAD'
}